build:
  stage: build
  script:
    - chmod +x run.sh clean.sh
    - bash run.sh
    - docker build -t dockerserverapi ./Vakapay.ApiServer
    - docker run -d -p 5000:80 --restart unless-stopped dockerserverapi
    - bash clean.sh
  environment:
    name: staging