{{- range $i, $v := .Values.secret -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "trackableappname" (dict "chart" $ "suffix" $i) }}
  labels:
    app: {{ template "applabel" $ }}
    track: "{{ $.Values.application.track }}"
    tier: "{{ $i }}"
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}"
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
  appsettings.Production.json: {{ index $.Values.secret $i | b64enc | quote }}
---
{{- end -}}
